const questions = {
  level1: [
    "What do you think is the hardest part of what I do for a living?",
    "What's the first thing you noticed about me?",
    "Do you like kissing or hugging more?",
    "What do you like most that I do in bed?",
    "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
    "What is your favorite thing that I do for you?",
    "Do I look kind? Explain.",
    "What’s your favorite non-sex activity that we do together?",
    "Do I seem like more of a creative or analytical type? Explain.",
    "Do I seem like someone who would get a name tattooed on myself? Why or why not?",
    "Finish the sentence: Just by looking at you I'd think _____________.",
    "When did you know you wanted to kiss me?",
    "Do you think I've ever been fired from a job? If so, what for?",
    "What was your first impression of me?",
    "When was the last time you thought about me in a positive way? Explain.",
    "How would you describe what you think my type is in three words?",
    "What did you think about my first message?",
    "Between the two of us, who seems like the better texter? Explain.",
    "What does my Instagram tell you about me?",
    "Make an assumption about me",
    "What did you think after your first sexual experience?",
    "What was the best party you ever went to?",
    "What is your favorite sexual memory of us?",
    "What about me intrigues you?",
    "What do you think I'm most likely to splurge on?",
    "As a child, what do you think I wanted to be?",
    "Finish the sentence: just by looking at you I'd think ...",
    "Do you think I was popular in school? Explain.",
    "Do you think I fall in love easily why or why not",
    "What compliment do you think I hear the most?",
    "What is your favorite memory of dating me?",
    "Do you think I ever checked an Ex phone for evidence?",
    "What subject do you think I thrived at in school and did I fail any?",
    "As a child what do you think I wanted to be when I grow up?",
    "Do you think I was popular at school? Explain.",
    "Do I remind you of anyone you know?",
    "What do you think I'm most likely to splurge on?",
    "Am I someone you typically connect with? If so/not, what's your type?",
    "Do I intimidate you? Why or why not?",
    "Do you ever dream about me?",
    "What's your favorite song lyric that comes to your mind from the top of your head?",
    "As a child, what do you think I wanted to be?",
    "If you got sick, do you think I would be there to care for you?",
    "Write down your number one goal for the next month. Compare.",
    "What’s your favorite personality trait of your own?",
    "Which of your personality traits do you wish you could change?"
  ],
  level2: [
    "What's been your happiest memory this past year?",
    "What do you think we need to work on the most in our relationship?",
    "Have you changed your mind about anything recently?",
    "What is your favorite sexual fantasy?",
    "Which of your friends is most like you?",
    "What is your favorite sexual position?",
    "Do you ever think about me sexually during the day?",
    "What has been your earliest recollection of happiness?",
    "What lesson took you the longest to un-learn?",
    "Are you lying to yourself about anything?",
    "When did you know you wanted to be monogamous with me?",
    "What questions are you trying to answer most in your life right now?",
    "When was the last time you surprised yourself?",
    "What title would you give this chapter in your life?",
    "What do you crave more of?",
    "What is something I could do to make you trust me even more?",
    "What's the worst pain you have ever been in that wasn't physical?",
    "Has a stranger ever changed your life?",
    "What's your first loves name and the reason you fell in love with them?",
    "What would your younger self not believe about your life today?",
    "How would you describe the feeling of being in love with one word?",
    "What are you more afraid of: failure or success and why?",
    "What is a dream you let go of?",
    "If you could get to know someone in your life on a deeper level who would it be and why?",
    "What's your mom's name and what is the most beautiful thing about her?",
    "What part of your life works what part of your life hurts?",
    "How can you become a better person?",
    "Do you think the image you have of yourself matches the image other people see you as?",
    "Are you missing anyone right now? Do you think they miss you to?",
    "Do you think I intimidate others? Why or why not?",
    "When you are asked how are you, how often do you answer truthfully?",
    "What's the most unexplainable thing that happened to you?",
    "What's your father's name? And tell me one thing about him.",
    "If you could have it your way: who would you be with? Where would you be? What would you be doing?",
    "Describe your perfect day!",
    "When do you feel the most protected and taken care of?",
    "What can I do to make sure you feel safe with me?",
    "What dating advice would you give your younger self?",
    "How old do you feel emotionally?",
    "Will I find your Ex on your Insta feed? Why or why not?",
    "What's the most embarrassing thing that happened to you on a date?",
    "What could you have done better in previous relationships?",
    "Is there an image of yourself you try to project on a first date you wish you could let go of?",
    "What did the people who raised you teach you about love?",
    "Describe your perfect date.",
    "What has being single taught you about yourself?",
    "What's your least favorite question to be asked on a date? What do you wish you would be asked more?",
    "What are you passionate about?",
    "What are you not currently giving enough time to?",
    "Write down the three most important things to you in a relationship (30 sec) Compare.",
    "Write down a dating pet peeve (30 sec). Compare.",
  ],
  level3: [
    "Based on what you learned about me what would you recommend I read?",
    "Do you ever get jealous if you see me talking to/texting other people?",
    "What about me surprised you?",
    "What did you learn about marriage from your parents?",
    "Do you have any deal-breakers, things that would make you seriously reconsider our relationship?",
    "What do you think our most important similarities are?",
    "What do you think is one thing I could do that would drastically improve my life?",
    "How would you describe me to a stranger?",
    "When we hang out with friends/family, do I make you feel like you’re still my priority?",
    "What do you think do I fear the most?",
    "Where am I most qualified to give advice about?",
    "What about me is the hardest for you to understand?",
    "Admit something.",
    "What did you learn about physical affection from your parents?",
    "What’s the angriest you ever felt?",
    "What parts of yourself do you see in me?",
    "How does one earn your vulnerability?",
    "Dare your partner to do something out of their comfort zone next week.",
    "What do you recommend I should let go of?",
    "What has this conversation taught you about yourself?",
    "What do you think my defining characteristic is?",
    "Why do you think we met?",
    "When this game is over, what will be something you will remember about me?",
    "What do you think my weakness is?",
    "What is the best thing about our relationship?",
    "How do our personalities compliment each other?",
    "What do you think I should know about myself that perhaps I'm unaware of?",
    "What would make you feel closer to me?",
    "What do you admire most about me?",
    "What answer of mine made you light up?",
    "What's the most attractive quality about me that isn't physical?",
    "Am I like you expected me to be?",
    "What are your secret thoughts when you see me at the end of the day?",
    "Do you ever wish I could read your mind? When?",
    "What things about me make you know I’m the one for you?",
    "What do you admire most about me?",
    "Draw your favorite memory with me. Compare.",
  ],
};

module.exports = questions;
